// =============================================================================
// User API 路由注册
// =============================================================================
// 注册用户 API 服务的所有 HTTP 路由，包括:
//   - 公开路由（无需认证）: 注册、登录
//   - 受保护路由（需要 JWT 认证）: 获取用户信息
//
// 数据来源:
//   由 goctl 工具根据 API 定义文件自动生成
//
// 业务场景:
//   为用户 API 服务配置所有 HTTP 路由和中间件（如 JWT 认证）
//
// 路由列表:
//   - POST /v1/user/register - 用户注册（公开）
//   - POST /v1/user/login    - 用户登录（公开）
//   - GET  /v1/user/user     - 获取用户信息（需要 JWT 认证）
//
// 注意:
//   此文件由代码生成工具自动生成，请勿手动修改
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "imooc.com/easy-chat/apps/user/api/internal/handler/user"
	"imooc.com/easy-chat/apps/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册所有 HTTP 路由
// 将用户相关的 HTTP 路由注册到 REST 服务器
//
// 参数:
//   - server: REST 服务器实例
//   - serverCtx: 服务上下文（包含配置和依赖）
//
// 路由分组:
//   1. 公开路由组（无需认证）
//      - POST /v1/user/register - 用户注册
//      - POST /v1/user/login    - 用户登录
//
//   2. 受保护路由组（需要 JWT 认证）
//      - GET /v1/user/user - 获取当前用户信息
//      - 使用 JWT 中间件验证访问令牌
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 注册公开路由（无需认证）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	// 注册受保护路由（需要 JWT 认证）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret), // 添加 JWT 认证中间件
		rest.WithPrefix("/v1/user"),
	)
}
