// Code generated by goctl. DO NOT EDIT!
// =============================================================================
// IM Models - 聊天记录模型生成代码
// =============================================================================
// 由 goctl 工具自动生成，提供聊天记录的基础 CRUD 操作
//
// 接口:
//   - chatLogModel: 聊天记录基础操作接口
//
// 实现:
//   - defaultChatLogModel: 默认聊天记录模型实现
//
// 功能:
//   - 插入聊天记录
//   - 查询单条聊天记录
//   - 按发送时间范围查询聊天记录
//   - 批量查询聊天记录
//   - 更新聊天记录
//   - 更新已读状态
//   - 删除聊天记录
//
// =============================================================================
package immodels

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo/options"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// chatLogModel 聊天记录基础操作接口
// 定义了聊天记录的所有基础数据库操作方法
type chatLogModel interface {
	// Insert 插入一条聊天记录
	Insert(ctx context.Context, data *ChatLog) error

	// FindOne 根据 ID 查询单条聊天记录
	FindOne(ctx context.Context, id string) (*ChatLog, error)

	// ListBySendTime 按发送时间范围查询聊天记录
	ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, limit int64) ([]*ChatLog, error)

	// ListByMsgIds 根据消息 ID 列表批量查询聊天记录
	ListByMsgIds(ctx context.Context, msgIds []string) ([]*ChatLog, error)

	// Update 更新聊天记录
	Update(ctx context.Context, data *ChatLog) error

	// UpdateMakeRead 更新消息已读记录
	UpdateMakeRead(ctx context.Context, id primitive.ObjectID, readRecords []byte) error

	// Delete 删除聊天记录
	Delete(ctx context.Context, id string) error
}

// defaultChatLogModel 默认聊天记录模型实现
// 封装了 MongoDB 连接，实现 chatLogModel 接口的所有方法
type defaultChatLogModel struct {
	// conn MongoDB 模型连接
	conn *mon.Model
}

// newDefaultChatLogModel 创建默认聊天记录模型实例
// 内部构造函数，用于初始化 defaultChatLogModel
//
// 参数:
//   - conn: MongoDB 模型连接
//
// 返回:
//   - *defaultChatLogModel: 默认聊天记录模型实例
func newDefaultChatLogModel(conn *mon.Model) *defaultChatLogModel {
	return &defaultChatLogModel{conn: conn}
}

// Insert 插入一条聊天记录到数据库
// 将聊天消息持久化到 MongoDB
//
// 参数:
//   - ctx: 上下文对象，用于控制请求生命周期
//   - data: 待插入的聊天记录数据
//
// 返回:
//   - error: 插入失败时返回错误信息
func (m *defaultChatLogModel) Insert(ctx context.Context, data *ChatLog) error {
	//if !data.ID.IsZero() {
	//	data.ID = primitive.NewObjectID()
	//	data.CreateAt = time.Now()
	//	data.UpdateAt = time.Now()
	//}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

// FindOne 根据 ID 查询单条聊天记录
// 通过消息 ID 从数据库中检索完整的聊天记录信息
//
// 参数:
//   - ctx: 上下文对象
//   - id: 聊天记录的 ObjectID 十六进制字符串
//
// 返回:
//   - *ChatLog: 查询到的聊天记录
//   - error: 查询失败或记录不存在时返回错误
func (m *defaultChatLogModel) FindOne(ctx context.Context, id string) (*ChatLog, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data ChatLog

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新聊天记录
// 替换数据库中的整条聊天记录，自动更新 UpdateAt 时间戳
//
// 参数:
//   - ctx: 上下文对象
//   - data: 包含更新内容的聊天记录对象
//
// 返回:
//   - error: 更新失败时返回错误信息
func (m *defaultChatLogModel) Update(ctx context.Context, data *ChatLog) error {
	data.UpdateAt = time.Now()

	_, err := m.conn.ReplaceOne(ctx, bson.M{"_id": data.ID}, data)
	return err
}

// UpdateMakeRead 更新消息已读记录
// 仅更新消息的已读记录字段，不影响其他字段
//
// 参数:
//   - ctx: 上下文对象
//   - id: 聊天记录的 ObjectID
//   - readRecords: 已读记录的序列化数据
//
// 返回:
//   - error: 更新失败时返回错误信息
func (m *defaultChatLogModel) UpdateMakeRead(ctx context.Context, id primitive.ObjectID, readRecords []byte) error {
	_, err := m.conn.UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$set": bson.M{
		"readRecords": readRecords,
	}})
	return err
}

// Delete 删除聊天记录
// 从数据库中永久删除指定的聊天记录
//
// 参数:
//   - ctx: 上下文对象
//   - id: 聊天记录的 ObjectID 十六进制字符串
//
// 返回:
//   - error: 删除失败时返回错误信息
func (m *defaultChatLogModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
// ListByMsgIds 根据消息 ID 列表批量查询聊天记录
// 用于批量获取多条聊天记录，常用于消息引用、转发等场景
//
// 参数:
//   - ctx: 上下文对象
//   - msgIds: 消息 ID 列表（ObjectID 十六进制字符串数组）
//
// 返回:
//   - []*ChatLog: 查询到的聊天记录列表
//   - error: 查询失败时返回错误信息
func (m *defaultChatLogModel) ListByMsgIds(ctx context.Context, msgIds []string) ([]*ChatLog, error) {
	var data []*ChatLog

	ids := make([]primitive.ObjectID, 0, len(msgIds))
	for _, id := range msgIds {
		oid, _ := primitive.ObjectIDFromHex(id)
		ids = append(ids, oid)
	}

	filter := bson.M{
		"_id": bson.M{
			"$in": ids,
		},
	}

	err := m.conn.Find(ctx, &data, filter)
	switch err {
	case nil:
		return data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// ListBySendTime 按发送时间范围查询聊天记录
// 用于分页加载聊天历史记录，支持时间范围过滤和数量限制
//
// 查询逻辑:
//   - 按发送时间倒序排列（最新的消息在前）
//   - 支持向前翻页（endSendTime > 0）和向后翻页（endSendTime = 0）
//   - 默认限制返回 100 条记录
//
// 参数:
//   - ctx: 上下文对象
//   - conversationId: 会话 ID，指定要查询的会话
//   - startSendTime: 起始时间戳（毫秒），查询小于此时间的消息
//   - endSendTime: 结束时间戳（毫秒），为 0 时表示不限制结束时间
//   - limit: 返回记录数量限制，为 0 时使用默认限制
//
// 返回:
//   - []*ChatLog: 查询到的聊天记录列表
//   - error: 查询失败时返回错误信息
func (m *defaultChatLogModel) ListBySendTime(ctx context.Context, conversationId string, startSendTime, endSendTime, limit int64) ([]*ChatLog, error) {
	var data []*ChatLog

	opt := options.FindOptions{
		Limit: &DefaultChatLogLimit,
		Sort: bson.M{
			"sendTime": -1,
		},
	}
	if limit > 0 {
		opt.Limit = &limit
	}

	filter := bson.M{
		"conversationId": conversationId,
	}

	if endSendTime > 0 {
		filter["sendTime"] = bson.M{
			"$gt":  endSendTime,
			"$lte": startSendTime,
		}
	} else {
		filter["sendTime"] = bson.M{
			"$lt": startSendTime,
		}
	}
	err := m.conn.Find(ctx, &data, filter, &opt)
	switch err {
	case nil:
		return data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
