// Code generated by goctl. DO NOT EDIT!
// =============================================================================
// IM Models - 用户会话列表模型生成代码
// =============================================================================
// 由 goctl 工具自动生成，提供用户会话列表的基础 CRUD 操作
//
// 接口:
//   - conversationsModel: 用户会话列表基础操作接口
//
// 实现:
//   - defaultConversationsModel: 默认用户会话列表模型实现
//
// 功能:
//   - 插入用户会话列表
//   - 查询用户会话列表
//   - 更新用户会话列表
//   - 删除用户会话列表
//   - 根据用户 ID 查询会话列表
//
// =============================================================================
package immodels

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo/options"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// conversationsModel 用户会话列表基础操作接口
// 定义了用户会话列表的所有基础数据库操作方法
type conversationsModel interface {
	// Insert 插入用户会话列表
	Insert(ctx context.Context, data *Conversations) error

	// FindOne 根据 ObjectID 查询用户会话列表
	FindOne(ctx context.Context, id string) (*Conversations, error)

	// Update 更新用户会话列表
	Update(ctx context.Context, data *Conversations) error

	// Delete 删除用户会话列表
	Delete(ctx context.Context, id string) error

	// FindByUserId 根据用户 ID 查询用户会话列表
	FindByUserId(ctx context.Context, uid string) (*Conversations, error)
}

// defaultConversationsModel 默认用户会话列表模型实现
// 封装了 MongoDB 连接，实现 conversationsModel 接口的所有方法
type defaultConversationsModel struct {
	// conn MongoDB 模型连接
	conn *mon.Model
}

// newDefaultConversationsModel 创建默认用户会话列表模型实例
// 内部构造函数，用于初始化 defaultConversationsModel
//
// 参数:
//   - conn: MongoDB 模型连接
//
// 返回:
//   - *defaultConversationsModel: 默认用户会话列表模型实例
func newDefaultConversationsModel(conn *mon.Model) *defaultConversationsModel {
	return &defaultConversationsModel{conn: conn}
}

// Insert 插入用户会话列表到数据库
// 如果文档 ID 为空，自动生成新的 ObjectID 和时间戳
//
// 参数:
//   - ctx: 上下文对象，用于控制请求生命周期
//   - data: 待插入的用户会话列表数据
//
// 返回:
//   - error: 插入失败时返回错误信息
func (m *defaultConversationsModel) Insert(ctx context.Context, data *Conversations) error {
	if !data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

// FindOne 根据 ObjectID 查询用户会话列表
// 通过 MongoDB 文档 ID 查询用户的会话列表
//
// 参数:
//   - ctx: 上下文对象
//   - id: 文档的 ObjectID 十六进制字符串
//
// 返回:
//   - *Conversations: 查询到的用户会话列表
//   - error: 查询失败或记录不存在时返回错误
func (m *defaultConversationsModel) FindOne(ctx context.Context, id string) (*Conversations, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Conversations

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新用户会话列表
// 使用 upsert 模式，如果文档不存在则插入，存在则更新
// 自动更新 UpdateAt 时间戳
//
// 参数:
//   - ctx: 上下文对象
//   - data: 包含更新内容的用户会话列表对象
//
// 返回:
//   - error: 更新失败时返回错误信息
func (m *defaultConversationsModel) Update(ctx context.Context, data *Conversations) error {
	data.UpdateAt = time.Now()

	_, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{
		"$set": data,
	}, options.Update().SetUpsert(true))
	return err
}

// Delete 删除用户会话列表
// 从数据库中永久删除指定用户的会话列表
//
// 参数:
//   - ctx: 上下文对象
//   - id: 文档的 ObjectID 十六进制字符串
//
// 返回:
//   - error: 删除失败时返回错误信息
func (m *defaultConversationsModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}

// FindByUserId 根据用户 ID 查询用户会话列表
// 通过 userId 字段查询指定用户的所有会话信息
// 这是最常用的查询方法，用于获取用户的会话列表
//
// 参数:
//   - ctx: 上下文对象
//   - uid: 用户 ID
//
// 返回:
//   - *Conversations: 查询到的用户会话列表
//   - error: 查询失败或记录不存在时返回错误
func (m *defaultConversationsModel) FindByUserId(ctx context.Context, uid string) (*Conversations, error) {
	var data Conversations

	err := m.conn.FindOne(ctx, &data, bson.M{"userId": uid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
