// Code generated by goctl. DO NOT EDIT!
// =============================================================================
// IM Models - 会话模型生成代码
// =============================================================================
// 由 goctl 工具自动生成，提供会话的基础 CRUD 操作
//
// 接口:
//   - conversationModel: 会话基础操作接口
//
// 实现:
//   - defaultConversationModel: 默认会话模型实现
//
// 功能:
//   - 插入会话
//   - 查询单个会话
//   - 批量查询会话
//   - 更新会话
//   - 更新会话消息
//   - 删除会话
//
// =============================================================================
package immodels

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// conversationModel 会话基础操作接口
// 定义了会话的所有基础数据库操作方法
type conversationModel interface {
	// Insert 插入一个会话
	Insert(ctx context.Context, data *Conversation) error

	// FindOne 根据会话 ID 查询单个会话
	FindOne(ctx context.Context, id string) (*Conversation, error)

	// Update 更新会话信息
	Update(ctx context.Context, data *Conversation) error

	// Delete 删除会话
	Delete(ctx context.Context, id string) error

	// ListByConversationIds 根据会话 ID 列表批量查询会话
	ListByConversationIds(ctx context.Context, ids []string) ([]*Conversation, error)

	// UpdateMsg 更新会话的最新消息和消息计数
	UpdateMsg(ctx context.Context, chatLog *ChatLog) error
}

// defaultConversationModel 默认会话模型实现
// 封装了 MongoDB 连接，实现 conversationModel 接口的所有方法
type defaultConversationModel struct {
	// conn MongoDB 模型连接
	conn *mon.Model
}

// newDefaultConversationModel 创建默认会话模型实例
// 内部构造函数，用于初始化 defaultConversationModel
//
// 参数:
//   - conn: MongoDB 模型连接
//
// 返回:
//   - *defaultConversationModel: 默认会话模型实例
func newDefaultConversationModel(conn *mon.Model) *defaultConversationModel {
	return &defaultConversationModel{conn: conn}
}

// Insert 插入一个会话到数据库
// 如果会话 ID 为空，自动生成新的 ObjectID 和时间戳
//
// 参数:
//   - ctx: 上下文对象，用于控制请求生命周期
//   - data: 待插入的会话数据
//
// 返回:
//   - error: 插入失败时返回错误信息
func (m *defaultConversationModel) Insert(ctx context.Context, data *Conversation) error {
	if !data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

// FindOne 根据会话 ID 查询单个会话
// 通过 conversationId 字段查询会话信息
//
// 参数:
//   - ctx: 上下文对象
//   - id: 会话 ID（非 ObjectID，而是业务层的 conversationId）
//
// 返回:
//   - *Conversation: 查询到的会话信息
//   - error: 查询失败或记录不存在时返回错误
func (m *defaultConversationModel) FindOne(ctx context.Context, id string) (*Conversation, error) {
	var data Conversation

	err := m.conn.FindOne(ctx, &data, bson.M{"conversationId": id})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update 更新会话信息
// 替换数据库中的整个会话文档，自动更新 UpdateAt 时间戳
//
// 参数:
//   - ctx: 上下文对象
//   - data: 包含更新内容的会话对象
//
// 返回:
//   - error: 更新失败时返回错误信息
func (m *defaultConversationModel) Update(ctx context.Context, data *Conversation) error {
	data.UpdateAt = time.Now()

	_, err := m.conn.ReplaceOne(ctx, bson.M{"_id": data.ID}, data)
	return err
}

// Delete 删除会话
// 从数据库中永久删除指定的会话
//
// 参数:
//   - ctx: 上下文对象
//   - id: 会话的 ObjectID 十六进制字符串
//
// 返回:
//   - error: 删除失败时返回错误信息
func (m *defaultConversationModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
// ListByConversationIds 根据会话 ID 列表批量查询会话
// 用于批量获取多个会话的信息
//
// 参数:
//   - ctx: 上下文对象
//   - ids: 会话 ID 列表（conversationId 数组）
//
// 返回:
//   - []*Conversation: 查询到的会话列表
//   - error: 查询失败时返回错误信息
func (m *defaultConversationModel) ListByConversationIds(ctx context.Context, ids []string) ([]*Conversation, error) {
	var data []*Conversation

	err := m.conn.Find(ctx, &data, bson.M{
		"conversationId": bson.M{
			"$in": ids,
		},
	})
	switch err {
	case nil:
		return data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// UpdateMsg 更新会话的最新消息和消息计数
// 当有新消息发送时，更新会话的最新消息内容并增加消息总数
//
// 更新操作:
//   - $inc: 将会话的消息总数加 1
//   - $set: 更新会话的最新消息为当前消息
//
// 参数:
//   - ctx: 上下文对象
//   - chatLog: 新发送的聊天消息
//
// 返回:
//   - error: 更新失败时返回错误信息
func (m *defaultConversationModel) UpdateMsg(ctx context.Context, chatLog *ChatLog) error {
	_, err := m.conn.UpdateOne(ctx,
		bson.M{"conversationId": chatLog.ConversationId},
		bson.M{
			// 更新会话总消息数
			"$inc": bson.M{"total": 1},
			"$set": bson.M{"msg": chatLog},
		},
	)
	return err
}
