// =============================================================================
// Social RPC 服务器实现
// =============================================================================
// 实现 gRPC 服务器接口，包括:
//   - 好友相关接口（申请、处理、列表查询）
//   - 群组相关接口（创建、申请、处理、列表查询、成员查询）
//
// 职责:
//   作为 gRPC 服务的入口，接收客户端请求，调用业务逻辑层处理
//
// 代码生成:
//   本文件由 goctl 工具自动生成，请勿手动修改
// =============================================================================
// Code generated by goctl. DO NOT EDIT!
// Source: social.proto

package server

import (
	"context"

	"imooc.com/easy-chat/apps/social/rpc/internal/logic"
	"imooc.com/easy-chat/apps/social/rpc/internal/svc"
	"imooc.com/easy-chat/apps/social/rpc/social"
)

// SocialServer gRPC 服务器结构
type SocialServer struct {
	svcCtx *svc.ServiceContext              // 服务上下文
	social.UnimplementedSocialServer        // 未实现的服务方法（用于向前兼容）
}

// NewSocialServer 创建 gRPC 服务器实例
//
// 参数:
//   - svcCtx: 服务上下文
//
// 返回:
//   - *SocialServer: 初始化完成的服务器实例
func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// FriendPutIn 处理好友申请请求
func (s *SocialServer) FriendPutIn(ctx context.Context, in *social.FriendPutInReq) (*social.FriendPutInResp, error) {
	l := logic.NewFriendPutInLogic(ctx, s.svcCtx)
	return l.FriendPutIn(in)
}

// FriendPutInHandle 处理好友申请处理请求
func (s *SocialServer) FriendPutInHandle(ctx context.Context, in *social.FriendPutInHandleReq) (*social.FriendPutInHandleResp, error) {
	l := logic.NewFriendPutInHandleLogic(ctx, s.svcCtx)
	return l.FriendPutInHandle(in)
}

// FriendPutInList 处理好友申请列表查询请求
func (s *SocialServer) FriendPutInList(ctx context.Context, in *social.FriendPutInListReq) (*social.FriendPutInListResp, error) {
	l := logic.NewFriendPutInListLogic(ctx, s.svcCtx)
	return l.FriendPutInList(in)
}

// FriendList 处理好友列表查询请求
func (s *SocialServer) FriendList(ctx context.Context, in *social.FriendListReq) (*social.FriendListResp, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

// GroupCreate 处理群组创建请求
func (s *SocialServer) GroupCreate(ctx context.Context, in *social.GroupCreateReq) (*social.GroupCreateResp, error) {
	l := logic.NewGroupCreateLogic(ctx, s.svcCtx)
	return l.GroupCreate(in)
}

// GroupPutin 处理群组入群申请请求
func (s *SocialServer) GroupPutin(ctx context.Context, in *social.GroupPutinReq) (*social.GroupPutinResp, error) {
	l := logic.NewGroupPutinLogic(ctx, s.svcCtx)
	return l.GroupPutin(in)
}

// GroupPutinList 处理群组申请列表查询请求
func (s *SocialServer) GroupPutinList(ctx context.Context, in *social.GroupPutinListReq) (*social.GroupPutinListResp, error) {
	l := logic.NewGroupPutinListLogic(ctx, s.svcCtx)
	return l.GroupPutinList(in)
}

// GroupPutInHandle 处理群组入群申请处理请求
func (s *SocialServer) GroupPutInHandle(ctx context.Context, in *social.GroupPutInHandleReq) (*social.GroupPutInHandleResp, error) {
	l := logic.NewGroupPutInHandleLogic(ctx, s.svcCtx)
	return l.GroupPutInHandle(in)
}

// GroupList 处理群组列表查询请求
func (s *SocialServer) GroupList(ctx context.Context, in *social.GroupListReq) (*social.GroupListResp, error) {
	l := logic.NewGroupListLogic(ctx, s.svcCtx)
	return l.GroupList(in)
}

// GroupUsers 处理群组成员查询请求
func (s *SocialServer) GroupUsers(ctx context.Context, in *social.GroupUsersReq) (*social.GroupUsersResp, error) {
	l := logic.NewGroupUsersLogic(ctx, s.svcCtx)
	return l.GroupUsers(in)
}
