// =============================================================================
// 路由注册 - Social API 路由配置
// =============================================================================
// 注册所有 Social API 的 HTTP 路由
//
// 路由分组:
//   1. 好友管理路由（/v1/social/friend/*）
//      - POST   /friend/putIn        发送好友申请
//      - PUT    /friend/putIn        处理好友申请（同意/拒绝）
//      - GET    /friend/putIns       获取好友申请列表
//      - GET    /friends             获取好友列表
//      - GET    /friends/online      查询好友在线状态
//
//   2. 群组管理路由（/v1/social/group/*）
//      - POST   /group               创建群组
//      - POST   /group/putIn         发送入群申请
//      - PUT    /group/putIn         处理入群申请（同意/拒绝）
//      - GET    /group/putIns        获取入群申请列表
//      - GET    /groups              获取群组列表
//      - GET    /group/users         获取群成员列表
//      - GET    /group/users/online  查询群成员在线状态
//
// 中间件配置:
//   - JWT 认证: 所有路由都需要 JWT token 认证
//   - 幂等性中间件: 群组路由启用幂等性控制
//   - 限流中间件: 群组路由启用限流控制
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	friend "imooc.com/easy-chat/apps/social/api/internal/handler/friend"
	group "imooc.com/easy-chat/apps/social/api/internal/handler/group"
	"imooc.com/easy-chat/apps/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册所有 HTTP 路由
// 配置路由路径、处理器、中间件和认证
//
// 参数:
//   - server: REST 服务器实例
//   - serverCtx: 服务上下文，包含配置和依赖
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 注册好友管理路由
	// 路径前缀: /v1/social
	// 认证: JWT token
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/friend/putIn",
				Handler: friend.FriendPutInHandleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/putIns",
				Handler: friend.FriendPutInListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: friend.FriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friends/online",
				Handler: friend.FriendsOnlineHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)

	// 注册群组管理路由
	// 路径前缀: /v1/social
	// 认证: JWT token
	// 中间件: 幂等性中间件、限流中间件
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IdempotenceMiddleware, serverCtx.LimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/group",
					Handler: group.CreateGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/putIn",
					Handler: group.GroupPutInHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/group/putIn",
					Handler: group.GroupPutInHandleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/putIns",
					Handler: group.GroupPutInListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups",
					Handler: group.GroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/users",
					Handler: group.GroupUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/users/online",
					Handler: group.GroupUserOnlineHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/social"),
	)
}
