// =============================================================================
// 路由注册 - HTTP 路由配置
// =============================================================================
// 注册所有 IM API 的 HTTP 路由，包括:
//   - GET  /v1/im/chatlog/readRecords - 获取消息已读记录
//   - GET  /v1/im/chatlog - 获取聊天记录
//   - POST /v1/im/setup/conversation - 建立用户会话
//   - GET  /v1/im/conversation - 获取会话列表
//   - PUT  /v1/im/conversation - 更新会话列表
//
// 路由特性:
//   - 所有路由都需要 JWT 认证
//   - 统一前缀: /v1/im
//
// 注意:
//   - 此文件由 goctl 工具自动生成，请勿手动修改
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"imooc.com/easy-chat/apps/im/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册所有 HTTP 路由
// 将所有 API 接口注册到 go-zero REST 服务器
//
// 参数:
//   - server: go-zero REST 服务器实例
//   - serverCtx: 服务上下文，包含所有依赖项
//
// 路由分组:
//  1. 消息已读记录路由（单独分组）
//  2. 聊天记录和会话管理路由（统一分组）
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 路由组 1: 消息已读记录接口
	// 需要 JWT 认证，路径前缀: /v1/im
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chatlog/readRecords", // GET /v1/im/chatlog/readRecords
				Handler: getChatLogReadRecordsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret), // JWT 认证中间件
		rest.WithPrefix("/v1/im"),                           // 路径前缀
	)

	// 路由组 2: 聊天记录和会话管理接口
	// 需要 JWT 认证，路径前缀: /v1/im
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chatlog", // GET /v1/im/chatlog
				Handler: getChatLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/setup/conversation", // POST /v1/im/setup/conversation
				Handler: setUpUserConversationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversation", // GET /v1/im/conversation
				Handler: getConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/conversation", // PUT /v1/im/conversation
				Handler: putConversationsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret), // JWT 认证中间件
		rest.WithPrefix("/v1/im"),                           // 路径前缀
	)
}
