// =============================================================================
// User API 数据类型定义
// =============================================================================
// 定义用户 API 服务的请求和响应数据结构，包括:
//   - 用户信息结构（User）
//   - 用户注册请求和响应（RegisterReq/RegisterResp）
//   - 用户登录请求和响应（LoginReq/LoginResp）
//   - 用户详情请求和响应（UserInfoReq/UserInfoResp）
//
// 数据来源:
//   由 goctl 工具根据 API 定义文件自动生成
//
// 业务场景:
//   用于 HTTP API 层的数据传输，定义客户端请求参数和服务端响应格式
//
// 注意:
//   此文件由代码生成工具自动生成，请勿手动修改
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package types

// User 用户信息结构
type User struct {
	Id       string `json:"id"`       // 用户 ID（唯一标识）
	Mobile   string `json:"mobile"`   // 手机号码
	Nickname string `json:"nickname"` // 用户昵称
	Sex      byte   `json:"sex"`      // 性别（0: 未知, 1: 男, 2: 女）
	Avatar   string `json:"avatar"`   // 头像 URL
}

// RegisterReq 用户注册请求
type RegisterReq struct {
	Phone    string `json:"phone"`    // 手机号码（必填，用于登录和唯一标识）
	Password string `json:"password"` // 密码（必填，将进行加密存储）
	Nickname string `json:"nickname"` // 昵称（必填）
	Sex      byte   `json:"sex"`      // 性别（0: 未知, 1: 男, 2: 女）
	Avatar   string `json:"avatar"`   // 头像 URL（可选）
}

// RegisterResp 用户注册响应
type RegisterResp struct {
	Token  string `json:"token"`  // JWT 访问令牌（用于后续 API 调用）
	Expire int64  `json:"expire"` // 令牌过期时间（Unix 时间戳，秒）
}

// LoginReq 用户登录请求
type LoginReq struct {
	Phone    string `json:"phone"`    // 手机号码（必填）
	Password string `json:"password"` // 密码（必填）
}

// LoginResp 用户登录响应
type LoginResp struct {
	Token  string `json:"token"`  // JWT 访问令牌（用于后续 API 调用）
	Expire int64  `json:"expire"` // 令牌过期时间（Unix 时间戳，秒）
}

// UserInfoReq 获取用户信息请求
// 用户 ID 从 JWT token 中解析，无需传递参数
type UserInfoReq struct {
}

// UserInfoResp 获取用户信息响应
type UserInfoResp struct {
	Info User `json:"info"` // 用户详细信息
}
