// =============================================================================
// User RPC 客户端
// =============================================================================
// 定义用户 RPC 客户端的接口和实现，包括:
//   - 类型别名定义（简化导入）
//   - User 客户端接口（定义所有 RPC 方法）
//   - defaultUser 客户端实现（封装 gRPC 调用）
//
// 数据来源:
//   由 goctl 工具根据 proto 文件自动生成
//
// 业务场景:
//   为 API 层和其他服务提供用户 RPC 客户端，简化 RPC 调用
//
// 使用方式:
//   client := userclient.NewUser(zrpc.MustNewClient(config))
//   resp, err := client.Login(ctx, &userclient.LoginReq{...})
//
// 注意:
//   此文件由代码生成工具自动生成，请勿手动修改
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"imooc.com/easy-chat/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// 类型别名定义（简化导入，避免重复引用 user 包）
	FindUserReq     = user.FindUserReq     // 查找用户请求
	FindUserResp    = user.FindUserResp    // 查找用户响应
	GetUserInfoReq  = user.GetUserInfoReq  // 获取用户信息请求
	GetUserInfoResp = user.GetUserInfoResp // 获取用户信息响应
	LoginReq        = user.LoginReq        // 登录请求
	LoginResp       = user.LoginResp       // 登录响应
	RegisterReq     = user.RegisterReq     // 注册请求
	RegisterResp    = user.RegisterResp    // 注册响应
	Request         = user.Request         // Ping 请求
	Response        = user.Response        // Ping 响应
	UserEntity      = user.UserEntity      // 用户实体

	// User 用户 RPC 客户端接口
	// 定义所有用户相关的 RPC 方法
	User interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)                      // 健康检查
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)                   // 用户登录
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)          // 用户注册
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) // 获取用户信息
		FindUser(ctx context.Context, in *FindUserReq, opts ...grpc.CallOption) (*FindUserResp, error)          // 查找用户
	}

	// defaultUser 默认用户 RPC 客户端实现
	defaultUser struct {
		cli zrpc.Client // gRPC 客户端连接
	}
)

// NewUser 创建用户 RPC 客户端实例
//
// 参数:
//   - cli: gRPC 客户端连接
//
// 返回:
//   - User: 用户 RPC 客户端接口
func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// Ping 健康检查
// 用于检查 RPC 服务是否正常运行
//
// 参数:
//   - ctx: 请求上下文
//   - in: Ping 请求参数
//   - opts: gRPC 调用选项
//
// 返回:
//   - *Response: Pong 响应
//   - error: 错误信息
func (m *defaultUser) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// Login 用户登录
// 验证用户凭证并返回访问令牌
//
// 参数:
//   - ctx: 请求上下文
//   - in: 登录请求参数（包含手机号、密码）
//   - opts: gRPC 调用选项
//
// 返回:
//   - *LoginResp: 登录响应（包含 JWT token 和过期时间）
//   - error: 错误信息
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// Register 用户注册
// 创建新用户并返回访问令牌
//
// 参数:
//   - ctx: 请求上下文
//   - in: 注册请求参数（包含手机号、密码、昵称、性别、头像）
//   - opts: gRPC 调用选项
//
// 返回:
//   - *RegisterResp: 注册响应（包含 JWT token 和过期时间）
//   - error: 错误信息
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// GetUserInfo 获取用户信息
// 根据用户 ID 获取用户详细信息
//
// 参数:
//   - ctx: 请求上下文
//   - in: 获取用户信息请求参数（包含用户 ID）
//   - opts: gRPC 调用选项
//
// 返回:
//   - *GetUserInfoResp: 用户信息响应
//   - error: 错误信息
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// FindUser 查找用户
// 支持根据手机号、昵称或 ID 列表查找用户
//
// 参数:
//   - ctx: 请求上下文
//   - in: 查找用户请求参数（支持手机号/昵称/ID 列表）
//   - opts: gRPC 调用选项
//
// 返回:
//   - *FindUserResp: 用户列表响应
//   - error: 错误信息
func (m *defaultUser) FindUser(ctx context.Context, in *FindUserReq, opts ...grpc.CallOption) (*FindUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindUser(ctx, in, opts...)
}
