// =============================================================================
// Social RPC 客户端
// =============================================================================
// 社交服务 RPC 客户端，提供:
//   - 好友相关接口调用（申请、处理、列表查询）
//   - 群组相关接口调用（创建、申请、处理、列表查询、成员查询）
//   - 类型别名定义（简化客户端使用）
//
// 使用方式:
//   1. 创建 zrpc.Client 实例
//   2. 调用 NewSocial 创建客户端
//   3. 调用相应的接口方法
//
// 代码生成:
//   本文件由 goctl 工具自动生成，请勿手动修改
// =============================================================================
// Code generated by goctl. DO NOT EDIT!
// Source: social.proto

package socialclient

import (
	"context"

	"imooc.com/easy-chat/apps/social/rpc/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// 类型别名定义，简化客户端使用
	FriendListReq         = social.FriendListReq         // 好友列表查询请求
	FriendListResp        = social.FriendListResp        // 好友列表查询响应
	FriendPutInHandleReq  = social.FriendPutInHandleReq  // 好友申请处理请求
	FriendPutInHandleResp = social.FriendPutInHandleResp // 好友申请处理响应
	FriendPutInListReq    = social.FriendPutInListReq    // 好友申请列表查询请求
	FriendPutInListResp   = social.FriendPutInListResp   // 好友申请列表查询响应
	FriendPutInReq        = social.FriendPutInReq        // 好友申请请求
	FriendPutInResp       = social.FriendPutInResp       // 好友申请响应
	FriendRequests        = social.FriendRequests        // 好友申请记录
	Friends               = social.Friends               // 好友关系记录
	GroupCreateReq        = social.GroupCreateReq        // 群组创建请求
	GroupCreateResp       = social.GroupCreateResp       // 群组创建响应
	GroupListReq          = social.GroupListReq          // 群组列表查询请求
	GroupListResp         = social.GroupListResp         // 群组列表查询响应
	GroupMembers          = social.GroupMembers          // 群组成员记录
	GroupPutInHandleReq   = social.GroupPutInHandleReq   // 群组入群申请处理请求
	GroupPutInHandleResp  = social.GroupPutInHandleResp  // 群组入群申请处理响应
	GroupPutinListReq     = social.GroupPutinListReq     // 群组申请列表查询请求
	GroupPutinListResp    = social.GroupPutinListResp    // 群组申请列表查询响应
	GroupPutinReq         = social.GroupPutinReq         // 群组入群申请请求
	GroupPutinResp        = social.GroupPutinResp        // 群组入群申请响应
	GroupRequests         = social.GroupRequests         // 群组申请记录
	GroupUsersReq         = social.GroupUsersReq         // 群组成员查询请求
	GroupUsersResp        = social.GroupUsersResp        // 群组成员查询响应
	Groups                = social.Groups                // 群组信息记录

	// Social 社交服务客户端接口
	Social interface {
		FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error)             // 好友申请
		FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) // 好友申请处理
		FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error)       // 好友申请列表查询
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)                      // 好友列表查询
		GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error)                   // 群组创建
		GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error)                      // 群组入群申请
		GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)          // 群组申请列表查询
		GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error)    // 群组入群申请处理
		GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error)                         // 群组列表查询
		GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error)                      // 群组成员查询
	}

	// defaultSocial 默认社交服务客户端实现
	defaultSocial struct {
		cli zrpc.Client // gRPC 客户端
	}
)

// NewSocial 创建社交服务客户端实例
//
// 参数:
//   - cli: zrpc 客户端实例
//
// 返回:
//   - Social: 社交服务客户端接口
func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// FriendPutIn 好友申请
func (m *defaultSocial) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutIn(ctx, in, opts...)
}

// FriendPutInHandle 好友申请处理
func (m *defaultSocial) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInHandle(ctx, in, opts...)
}

// FriendPutInList 好友申请列表查询
func (m *defaultSocial) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInList(ctx, in, opts...)
}

// FriendList 好友列表查询
func (m *defaultSocial) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

// GroupCreate 群组创建
func (m *defaultSocial) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupCreate(ctx, in, opts...)
}

// GroupPutin 群组入群申请
func (m *defaultSocial) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutin(ctx, in, opts...)
}

// GroupPutinList 群组申请列表查询
func (m *defaultSocial) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutinList(ctx, in, opts...)
}

// GroupPutInHandle 群组入群申请处理
func (m *defaultSocial) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutInHandle(ctx, in, opts...)
}

// GroupList 群组列表查询
func (m *defaultSocial) GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupList(ctx, in, opts...)
}

// GroupUsers 群组成员查询
func (m *defaultSocial) GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...grpc.CallOption) (*GroupUsersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupUsers(ctx, in, opts...)
}
