// =============================================================================
// API 数据类型定义 - IM API 请求/响应结构
// =============================================================================
// 定义所有 API 接口的请求和响应数据结构，包括:
//   - 聊天记录相关（ChatLog、ChatLogReq、ChatLogResp）
//   - 会话管理相关（Conversation、GetConversationsReq/Resp、PutConversationsReq/Resp）
//   - 消息已读记录（GetChatLogReadRecordsReq/Resp）
//   - 会话建立（SetUpUserConversationReq/Resp）
//
// 注意:
//   - 此文件由 goctl 工具自动生成，请勿手动修改
//   - 如需修改，请编辑 .api 文件后重新生成
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package types

// ChatLog 聊天记录结构
// 表示单条聊天消息的完整信息
type ChatLog struct {
	Id             string `json:"id,omitempty"`             // 消息 ID（唯一标识）
	ConversationId string `json:"conversationId,omitempty"` // 会话 ID
	SendId         string `json:"sendId,omitempty"`         // 发送者用户 ID
	RecvId         string `json:"recvId,omitempty"`         // 接收者 ID（单聊为用户 ID，群聊为群组 ID）
	MsgType        int32  `json:"msgType,omitempty"`        // 消息类型（1:文本 2:图片 3:语音 4:视频等）
	MsgContent     string `json:"msgContent,omitempty"`     // 消息内容
	ChatType       int32  `json:"chatType,omitempty"`       // 聊天类型（1:单聊 2:群聊）
	SendTime       int64  `json:"SendTime,omitempty"`       // 发送时间（Unix 时间戳）
}

// Conversation 会话结构
// 表示用户的一个聊天会话（单聊或群聊）
type Conversation struct {
	ConversationId string `json:"conversationId,omitempty"` // 会话 ID（唯一标识）
	ChatType       int32  `json:"ChatType,omitempty"`       // 聊天类型（1:单聊 2:群聊）
	TargetId       string `json:"targetId,omitempty"`       // 目标 ID（单聊为对方用户 ID，群聊为群组 ID）
	IsShow         bool   `json:"isShow,omitempty"`         // 是否显示（用于会话隐藏功能）
	Seq            int64  `json:"seq,omitempty"`            // 会话序列号（用于排序）
	Read           int32  `json:"read,omitempty"`           // 已读消息数
	Total          int32  `json:"total,omitempty"`          // 总消息数
	Unread         int32  `json:"unread,omitempty"`         // 未读消息数
}

// GetChatLogReadRecordsReq 获取消息已读记录请求
// 查询指定消息的已读/未读用户列表
type GetChatLogReadRecordsReq struct {
	MsgId string `json:"msgId"` // 消息 ID
}

// GetChatLogReadRecordsResp 获取消息已读记录响应
// 返回已读和未读用户的手机号列表
type GetChatLogReadRecordsResp struct {
	Reads   []string `json:"reads"`   // 已读用户手机号列表
	UnReads []string `json:"unReads"` // 未读用户手机号列表
}

// ChatLogReq 获取聊天记录请求
// 查询指定会话的聊天记录
type ChatLogReq struct {
	ConversationId string `json:"conversationId"`         // 会话 ID（必填）
	StartSendTime  int64  `json:"startSendTime,omitempty"` // 开始时间（Unix 时间戳，可选）
	EndSendTime    int64  `json:"endSendTime,omitempty"`   // 结束时间（Unix 时间戳，可选）
	Count          int64  `json:"count,omitempty"`         // 查询数量（可选，默认返回所有）
}

// ChatLogResp 获取聊天记录响应
// 返回聊天记录列表
type ChatLogResp struct {
	List []*ChatLog `json:"list"` // 聊天记录列表
}

// GetConversationsReq 获取会话列表请求
// 查询当前用户的所有会话
type GetConversationsReq struct {
	// 无请求参数，从 JWT Token 中获取用户 ID
}

// GetConversationsResp 获取会话列表响应
// 返回用户的所有会话信息
type GetConversationsResp struct {
	UserId           string                   `json:"userId"`           // 用户 ID
	ConversationList map[string]*Conversation `json:"conversationList"` // 会话列表（key: 会话 ID, value: 会话信息）
}

// PutConversationsReq 更新会话列表请求
// 批量更新用户的会话信息
type PutConversationsReq struct {
	ConversationList map[string]*Conversation `json:"conversationList"` // 会话列表（key: 会话 ID, value: 会话信息）
}

// PutConversationsResp 更新会话列表响应
type PutConversationsResp struct {
	// 无响应数据
}

// SetUpUserConversationReq 建立用户会话请求
// 创建或初始化一个新的会话
type SetUpUserConversationReq struct {
	SendId   string `json:"sendId,omitempty"`   // 发送者用户 ID
	RecvId   string `json:"recvId,omitempty"`   // 接收者 ID（单聊为用户 ID，群聊为群组 ID）
	ChatType int32  `json:"ChatType,omitempty"` // 聊天类型（1:单聊 2:群聊）
}

// SetUpUserConversationResp 建立用户会话响应
type SetUpUserConversationResp struct {
	// 无响应数据
}
