// =============================================================================
// Social API 类型定义 - 请求和响应数据结构
// =============================================================================
// 定义 Social API 所有接口的请求和响应数据结构
//
// 数据结构分类:
//   1. 好友相关:
//      - Friends: 好友信息
//      - FriendRequests: 好友申请记录
//      - FriendPutInReq/Resp: 发送好友申请
//      - FriendPutInHandleReq/Resp: 处理好友申请
//      - FriendPutInListReq/Resp: 好友申请列表
//      - FriendListReq/Resp: 好友列表
//      - FriendsOnlineReq/Resp: 好友在线状态
//
//   2. 群组相关:
//      - Groups: 群组信息
//      - GroupMembers: 群成员信息
//      - GroupRequests: 入群申请记录
//      - GroupCreateReq/Resp: 创建群组
//      - GroupPutInRep/Resp: 发送入群申请
//      - GroupPutInHandleRep/Resp: 处理入群申请
//      - GroupPutInListRep/Resp: 入群申请列表
//      - GroupListRep/Resp: 群组列表
//      - GroupUserListReq/Resp: 群成员列表
//      - GroupUserOnlineReq/Resp: 群成员在线状态
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT.
package types

// Friends 好友信息
type Friends struct {
	Id        int32  `json:"id,omitempty"`        // 好友关系 ID
	FriendUid string `json:"friend_uid,omitempty"` // 好友用户 ID
	Nickname  string `json:"nickname,omitempty"`   // 好友昵称
	Avatar    string `json:"avatar,omitempty"`     // 好友头像
	Remark    string `json:"remark,omitempty"`     // 备注名
}

// FriendRequests 好友申请记录
type FriendRequests struct {
	Id           int64  `json:"id,omitempty"`            // 申请记录 ID
	UserId       string `json:"user_id,omitempty"`       // 被申请人用户 ID
	ReqUid       string `json:"req_uid,omitempty"`       // 申请人用户 ID
	ReqMsg       string `json:"req_msg,omitempty"`       // 申请消息
	ReqTime      int64  `json:"req_time,omitempty"`      // 申请时间
	HandleResult int    `json:"handle_result,omitempty"` // 处理结果（0-待处理，1-已同意，2-已拒绝）
	HandleMsg    string `json:"handle_msg,omitempty"`    // 处理消息
}

// Groups 群组信息
type Groups struct {
	Id              string `json:"id,omitempty"`               // 群组 ID
	Name            string `json:"name,omitempty"`             // 群组名称
	Icon            string `json:"icon,omitempty"`             // 群组图标
	Status          int64  `json:"status,omitempty"`           // 群组状态
	GroupType       int64  `json:"group_type,omitempty"`       // 群组类型
	IsVerify        bool   `json:"is_verify,omitempty"`        // 是否需要验证
	Notification    string `json:"notification,omitempty"`     // 群公告
	NotificationUid string `json:"notification_uid,omitempty"` // 群公告发布者 ID
}

// GroupMembers 群成员信息
type GroupMembers struct {
	Id            int64  `json:"id,omitempty"`             // 成员记录 ID
	GroupId       string `json:"group_id,omitempty"`       // 群组 ID
	UserId        string `json:"user_id,omitempty"`        // 用户 ID
	Nickname      string `json:"nickname,omitempty"`       // 用户昵称
	UserAvatarUrl string `json:"user_avatar_url,omitempty"` // 用户头像
	RoleLevel     int    `json:"role_level,omitempty"`     // 角色等级（1-群主，2-管理员，3-普通成员）
	InviterUid    string `json:"inviter_uid,omitempty"`    // 邀请人 ID
	OperatorUid   string `json:"operator_uid,omitempty"`   // 操作人 ID
}

// GroupRequests 入群申请记录
type GroupRequests struct {
	Id            int64  `json:"id,omitempty"`             // 申请记录 ID
	UserId        string `json:"user_id,omitempty"`        // 申请人用户 ID
	GroupId       string `json:"group_id,omitempty"`       // 群组 ID
	ReqMsg        string `json:"req_msg,omitempty"`        // 申请消息
	ReqTime       int64  `json:"req_time,omitempty"`       // 申请时间
	JoinSource    int64  `json:"join_source,omitempty"`    // 加入来源
	InviterUserId string `json:"inviter_user_id,omitempty"` // 邀请人 ID
	HandleUserId  string `json:"handle_user_id,omitempty"`  // 处理人 ID
	HandleTime    int64  `json:"handle_time,omitempty"`     // 处理时间
	HandleResult  int64  `json:"handle_result,omitempty"`   // 处理结果（0-待处理，1-已同意，2-已拒绝）
}

// FriendPutInReq 发送好友申请请求
type FriendPutInReq struct {
	ReqMsg  string `json:"req_msg,omitempty"`  // 申请消息
	ReqTime int64  `json:"req_time,omitempty"` // 申请时间
	UserId  string `json:"user_uid"`           // 目标用户 ID
}

// FriendPutInResp 发送好友申请响应
type FriendPutInResp struct {
}

// FriendPutInHandleReq 处理好友申请请求
type FriendPutInHandleReq struct {
	FriendReqId  int32 `json:"friend_req_id,omitempty"`  // 好友申请记录 ID
	HandleResult int32 `json:"handle_result,omitempty"`  // 处理结果（1-同意，2-拒绝）
}

// FriendPutInHandleResp 处理好友申请响应
type FriendPutInHandleResp struct {
}

// FriendPutInListReq 好友申请列表请求
type FriendPutInListReq struct {
}

// FriendPutInListResp 好友申请列表响应
type FriendPutInListResp struct {
	List []*FriendRequests `json:"list"` // 好友申请列表
}

// FriendListReq 好友列表请求
type FriendListReq struct {
}

// FriendListResp 好友列表响应
type FriendListResp struct {
	List []*Friends `json:"list"` // 好友列表
}

// GroupCreateReq 创建群组请求
type GroupCreateReq struct {
	Name string `json:"name,omitempty"` // 群组名称
	Icon string `json:"icon,omitempty"` // 群组图标
}

// GroupCreateResp 创建群组响应
type GroupCreateResp struct {
}

// GroupPutInRep 发送入群申请请求
type GroupPutInRep struct {
	GroupId    string `json:"group_id,omitempty"`    // 群组 ID
	ReqMsg     string `json:"req_msg,omitempty"`     // 申请消息
	ReqTime    int64  `json:"req_time,omitempty"`    // 申请时间
	JoinSource int64  `json:"join_source,omitempty"` // 加入来源
}

// GroupPutInResp 发送入群申请响应
type GroupPutInResp struct {
}

// GroupPutInHandleRep 处理入群申请请求
type GroupPutInHandleRep struct {
	GroupReqId   int32  `json:"group_req_id,omitempty"`   // 入群申请记录 ID
	GroupId      string `json:"group_id,omitempty"`       // 群组 ID
	HandleResult int32  `json:"handle_result,omitempty"`  // 处理结果（1-同意，2-拒绝）
}

// GroupPutInHandleResp 处理入群申请响应
type GroupPutInHandleResp struct {
}

// GroupPutInListRep 入群申请列表请求
type GroupPutInListRep struct {
	GroupId string `json:"group_id,omitempty"` // 群组 ID
}

// GroupPutInListResp 入群申请列表响应
type GroupPutInListResp struct {
	List []*GroupRequests `json:"list,omitempty"` // 入群申请列表
}

// GroupListRep 群组列表请求
type GroupListRep struct {
}

// GroupListResp 群组列表响应
type GroupListResp struct {
	List []*Groups `json:"list,omitempty"` // 群组列表
}

// GroupUserListReq 群成员列表请求
type GroupUserListReq struct {
	GroupId string `json:"group_id,omitempty"` // 群组 ID
}

// GroupUserListResp 群成员列表响应
type GroupUserListResp struct {
	List []*GroupMembers `json:"List,omitempty"` // 群成员列表
}

// FriendsOnlineReq 好友在线状态请求
type FriendsOnlineReq struct {
}

// FriendsOnlineResp 好友在线状态响应
type FriendsOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"` // 在线状态映射表（用户ID -> 在线状态）
}

// GroupUserOnlineReq 群成员在线状态请求
type GroupUserOnlineReq struct {
	GroupId string `json:"group_id,omitempty"` // 群组 ID
}

// GroupUserOnlineResp 群成员在线状态响应
type GroupUserOnlineResp struct {
	OnlineList map[string]bool `json:"onLineList"` // 在线状态映射表（用户ID -> 在线状态）
}
