// =============================================================================
// User RPC 服务器
// =============================================================================
// 实现用户 RPC 服务的所有接口方法，包括:
//   - Ping: 健康检查
//   - Login: 用户登录
//   - Register: 用户注册
//   - GetUserInfo: 获取用户信息
//   - FindUser: 查找用户
//
// 数据来源:
//   由 goctl 工具根据 proto 文件自动生成
//
// 业务场景:
//   为 API 层和其他服务提供用户相关的 RPC 接口
//
// 注意:
//   此文件由代码生成工具自动生成，请勿手动修改
//
// =============================================================================
// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"imooc.com/easy-chat/apps/user/rpc/internal/logic"
	"imooc.com/easy-chat/apps/user/rpc/internal/svc"
	"imooc.com/easy-chat/apps/user/rpc/user"
)

// UserServer 用户 RPC 服务器结构
type UserServer struct {
	svcCtx *svc.ServiceContext // 服务上下文（包含配置和依赖）
	user.UnimplementedUserServer
}

// NewUserServer 创建用户 RPC 服务器实例
//
// 参数:
//   - svcCtx: 服务上下文
//
// 返回:
//   - *UserServer: 服务器实例
func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Ping 健康检查接口
// 用于检查服务是否正常运行
//
// 参数:
//   - ctx: 请求上下文
//   - in: Ping 请求参数
//
// 返回:
//   - *user.Response: Pong 响应
//   - error: 错误信息
func (s *UserServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// Login 用户登录接口
// 验证用户凭证并返回访问令牌
//
// 参数:
//   - ctx: 请求上下文
//   - in: 登录请求参数（包含手机号、密码）
//
// 返回:
//   - *user.LoginResp: 登录响应（包含 JWT token 和过期时间）
//   - error: 错误信息
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// Register 用户注册接口
// 创建新用户并返回访问令牌
//
// 参数:
//   - ctx: 请求上下文
//   - in: 注册请求参数（包含手机号、密码、昵称、性别、头像）
//
// 返回:
//   - *user.RegisterResp: 注册响应（包含 JWT token 和过期时间）
//   - error: 错误信息
func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// GetUserInfo 获取用户信息接口
// 根据用户 ID 获取用户详细信息
//
// 参数:
//   - ctx: 请求上下文
//   - in: 获取用户信息请求参数（包含用户 ID）
//
// 返回:
//   - *user.GetUserInfoResp: 用户信息响应
//   - error: 错误信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoReq) (*user.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// FindUser 查找用户接口
// 支持根据手机号、昵称或 ID 列表查找用户
//
// 参数:
//   - ctx: 请求上下文
//   - in: 查找用户请求参数（支持手机号/昵称/ID 列表）
//
// 返回:
//   - *user.FindUserResp: 用户列表响应
//   - error: 错误信息
func (s *UserServer) FindUser(ctx context.Context, in *user.FindUserReq) (*user.FindUserResp, error) {
	l := logic.NewFindUserLogic(ctx, s.svcCtx)
	return l.FindUser(in)
}
